console.log('DAS BUGURT!!!');
let temp02 = JSON.parse(sessionStorage.getItem("Iosif"));
console.log("Хиты: " + temp02.hp + "/" + temp02.fullHp);
let Gob01 = new Character(20, 20, 'Первый гоблин',"Первого гоблина", "Первому гоблину", "Первого гоблина", "Первым гоблином", "Первом гоблине", 10, 4, 20, '#', 0, 0, 0, 0);
let Gob02 = new Character(20, 17, 'Второй гоблин', "Второго гоблина", "Второму гоблину", "Второго гоблина", "Вторым гоблином", "Втором гоблине", 10, 4, 20, '#', 0, 0, 0, 0);
let Gob03 = new Character(20, 18, 'Третий гоблин',"Третьего гоблина", "Третьему гоблину", "Третьего гоблина", "Третьим гоблином", "Третьем гоблине", 10, 4, 20, '#', 0, 0, 0, 0);
let Gob04 = new Character(20, 19, 'Четвёртый гоблин', "Четвёртого гоблина", "Четвёртому гоблину", "Четвёртого гоблина", "Четвёртым гоблином", "Четвёртом гоблине", 10, 4, 20, '#', 0, 0, 0, 0);
let Gob05 = new Character(20, 16, 'Пятый гоблин', "Пятого гоблина", "Пятому гоблину", "Пятого гоблина", "Пятым гоблином", "Пятом гоблине", 10, 4, 20, '#', 0, 0, 0, 0);
let Gob06 = new Character(20, 17, 'Шестой гоблин', "Шестого гоблина", "Шестому гоблину", "Шестого гоблина", "Шестым гоблином", "Шестом гоблине", 10, 4, 20, '#', 0, 0, 0, 0);
let Gob07 = new Character(20, 19, 'Седьмой гоблин', "Седьмого гоблина", "Седьмому гоблину", "Седьмого гоблина", "Седьмым гоблином", "Седьмом гоблине", 10, 4, 20, '#', 0, 0, 0, 0);
let Gob08 = new Character(20, 10, 'Восьмой гоблин', "Восьмого гоблина", "Восьмому гоблину", "Восьмого гоблина", "Восьмым гоблином", "Восьмом гоблине", 10, 4, 20, '#', 0, 0, 0, 0);
let Gob09 = new Character(20, 17, 'Девятый гоблин', "Девятого гоблина", "Девятому гоблину", "Девятого гоблина", "Девятым гоблином", "Девятом гоблине", 10, 4, 20, '#', 0, 0, 0, 0);
let Gob10 = new Character(20, 16, 'Десятый гоблин', "Десятого гоблина", "Десятому гоблину", "Десятого гоблина", "Десятым гоблином", "Десятом гоблине", 10, 4, 20, '#', 0, 0, 0, 0);
let orda = [Gob01, Gob02, Gob03, Gob04, Gob05, Gob06, Gob07, Gob08, Gob09, Gob10];
orda.push(temp02);
massfight(orda, 10, 11);
document.write('<p>Противники готовы порезать вас на ленточки,<br> но вам уже почти нечего им противопоставить - силы на исходе.</p>');
sessionStorage.setItem("Gobbo01", JSON.stringify(Gob01));
sessionStorage.setItem("Gobbo02", JSON.stringify(Gob02));
sessionStorage.setItem("Gobbo03", JSON.stringify(Gob03));
sessionStorage.setItem("Gobbo04", JSON.stringify(Gob04));
sessionStorage.setItem("Gobbo05", JSON.stringify(Gob05));
sessionStorage.setItem("Gobbo06", JSON.stringify(Gob06));
sessionStorage.setItem("Gobbo07", JSON.stringify(Gob07));
sessionStorage.setItem("Gobbo08", JSON.stringify(Gob08));
sessionStorage.setItem("Gobbo09", JSON.stringify(Gob09));
sessionStorage.setItem("Gobbo10", JSON.stringify(Gob10));
sessionStorage.Iosif = JSON.stringify(temp02);